security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider: 
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider 
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login # where to redirect after logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
    - { path: ^/super_admin, roles: ROLE_SUPER_ADMIN } # Accès à Super Admin pour les super administrateurs
    - { path: ^/admin, roles: ROLE_ADMIN } # Accès à l'inscription pour les administrateurs
    - { path: ^/profile, roles: ROLE_EMPLOYE } # Accès aux profils pour les employés
    # - { path: ^/register, roles: ROLE_SUPER_ADMIN } # Accès à l'inscription uniquement pour le super administrateur 

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_EMPLOYE

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
